### ISSUE TITLE
Easier article definitions

### ISSUE THREAD

**Issue by dankempster** [dankempster/axstrad-article-bundle#1]
Currently configuration is

``` YAML
axstrad_article:
  definitions:
    my_article:
      entity: Acme\MyBundle\Entity\MyArticle
```

It be nice to be able to 

``` YAML
axstrad_article:
  definitions:
    my_article: Acme\MyBundle\Entity\MyArticle
```

Or even

``` YAML
axstrad_article:
    my_article: Acme\MyBundle\Entity\MyArticle
```
